### ISSUE TITLE
HackFS Judging

### ISSUE THREAD

**Issue by DeveloperAlly** [lordshashank/DatAgentDAO#7]
Hey There!

I notice you have used the Lilypad StableDiffusion example script in your code here.
Were you planning on implementing a Dreambooth example also?

**Comment by lordshashank** [comment]
Ya, actually our aim was to finetune as well as interact with the models through smart contracts i.e. changing the commands used in lilypad contracts so as to finetune as well as interact with the dreambooth example. We were working on it but the hackathon deadline arrived and we were not able to implement it in time frame, we really look forward to implement it in future and enable all functionalities in it.
